### ISSUE TITLE
Refactor code, get rid of deprecated methods and add NullPointerException checks.

### ISSUE THREAD

**Issue by moeux** [ferrixx/ferrixxBot#2]
The code inside your MessageListener is awfully long. Just one continuously chunck of code. Making it a pain to actually look at it and be able to maintain it.
You're using deprecated method when retrieving Timestamps.
You're missing a lot NPE checks inside your SQL code.

**Comment by ferrixx** [comment]
Fixed >Point 2 (missing NPE Checks inside my SQL Code) 

Working on > Point 1 (Deprecated Method when retrieving Timestamps)

Thanks for you Improvement and Issues Report!
